# Generated by Django 5.1.5 on 2025-02-12 09:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resim',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resim',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='resim',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
